const canYouNameIt = () => {
  const categories = [
    'cars',
    'makeup',
    'countries',
    'capitals',
    'movies',
    'tv-shows',
    'singers',
    'celebrities',
    'hairstyles',
    'athletes',
    'yoga positions',
    'elements',
    'scientists',
    'luxury brands',
    'rappers',
    'street-wear brands',
    'books',
    'snacks',
    'spices',
    'desserts',
    'animals',
    'places',
    'languages',
    'sports',
    'instruments',
    'flowers',
    "Countries",
  "Cities",
  "Animals",
  "Fruits",
  "Vegetables",
  "Movies",
  "TV Shows",
  "Books",
  "Famous People",
  "Brands",
  "Sports",
  "Songs",
  "Bands or Artists",
  "Occupations",
  "Cars",
  "Colors",
  "Flowers",
  "Drinks",
  "Foods",
  "Languages",
  "Planets",
  "Historical Events",
  "Landmarks",
  "Festivals",
  "Scientific Terms",
  "Tools",
  "Clothing Items",
  "Hobbies",
  "School Subjects",
  "Cartoon Characters",
  "Board Games",
  "Animals in the Ocean",
  "Types of Trees",
  "Countries' Capitals",
  "Superheroes",
  "Video Games",
  "Materials",
  "Insects",
  "Kitchen Appliances",
  "Weather Phenomena",
  "Gems or Minerals",
  "Means of Transport",
  "Musical Instruments",
  "Fairy Tales",
  "Mythical Creatures",
  "Religions",
  "Desserts",
  "Companies",
  "Fictional Places",
  "Historical Figures",
  "Body Parts",
  "Street Names",
  "Famous Paintings",
  "Types of Dances",
  "Birds",
  "Reptiles",
  "Board Game Titles",
  "Spices or Herbs",
  "Currencies",
  "Breakfast Foods",
  "Sea Creatures",
  "Modes of Travel",
  "Furniture",
  "Computer Terms",
  "Castles",
  "Languages Spoken",
  "Themes for Parties",
  "Characters from Books",
  "Technology Brands",
  "Wild Animals",
  "Pets",
  "Carnivals or Fairs",
  "Holidays",
  "Jobs or Professions",
  "Camping Gear",
  "Beverages",
  "Cheeses",
  "Flowers or Plants",
  "Toys",
  "Things in Space",
  "Pirates",
  "Fashion Accessories",
  "Online Platforms",
  "Famous Battles",
  "Mountains",
  "Movies from the 90s",
  "Genres of Music",
  "Fairy Tale Characters",
  "National Dishes",
  "Objects Found in Offices",
  "Items in the Kitchen",
  "Items of Jewelry",
  "Trees Found in Forests",
  "Horror Movie Villains",
  "Spacecrafts",
  "Types of Weather",
  "Famous Athletes",
  "Natural Disasters",
  ];

  const letter = String.fromCharCode(Math.floor(Math.random() * 26) + 65);

  const category = categories[Math.floor(Math.random() * categories.length)];

  document.getElementById('name-it-letter').innerHTML = letter;
  document.getElementById('name-it-category').innerHTML = category;
  document.getElementById('name-it-play').style.display = 'block';
};

document.getElementById('name-it-button').addEventListener('click', canYouNameIt);
document.getElementById('name-it-play').style.display = 'none';
